import Link from "next/link";
import { IconSparkles } from "@/components/icons";

export const metadata = {
  title: "Terms of Service – ProductMind",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <header className="border-b border-gray-200 bg-white">
        <div className="mx-auto flex max-w-3xl items-center gap-3 px-6 py-6">
          <Link href="/" className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-600">
              <IconSparkles className="h-4 w-4 text-white" />
            </div>
            <span className="text-lg font-bold text-gray-900">ProductMind</span>
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-12">
        <h1 className="text-3xl font-bold text-gray-900">Terms of Service</h1>
        <p className="mt-2 text-sm text-gray-500">Last updated: May 2026</p>

        <div className="mt-8 space-y-8 text-sm leading-relaxed text-gray-700">
          <section>
            <h2 className="text-lg font-semibold text-gray-900">1. Acceptance</h2>
            <p className="mt-2">
              By accessing or using ProductMind, you agree to be bound by these Terms of Service.
              If you do not agree, do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">2. Service description</h2>
            <p className="mt-2">
              ProductMind is an AI-powered product decision assistant currently in <strong>beta</strong>.
              It provides tools for generating PRDs, competitive analyses, roadmaps, feature
              prioritization, decision reviews, and strategic insights using artificial intelligence.
              The service is provided for informational and productivity purposes and is not a
              substitute for professional business, legal, or financial advice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">3. Beta status</h2>
            <p className="mt-2">
              ProductMind is in active development. Features, pricing, rate limits, and availability
              may change at any time. The service may be modified, suspended, or discontinued during
              the beta period without prior notice. We appreciate your feedback and patience as we
              improve the product.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">4. User responsibilities</h2>
            <p className="mt-2">
              You are responsible for maintaining the confidentiality of your account credentials
              and for all activities under your account. You agree not to:
            </p>
            <ul className="mt-2 list-inside list-disc space-y-1">
              <li>Use the service for unlawful, harmful, or fraudulent purposes</li>
              <li>Upload content that violates the rights of others</li>
              <li>Attempt to scrape, reverse-engineer, or overload the service</li>
              <li>Circumvent rate limits, authentication, or access controls</li>
              <li>Use automated tools to access the service without permission</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">5. AI-generated content</h2>
            <p className="mt-2">
              Content generated by AI is provided as-is for informational and decision-support
              purposes only. AI outputs are <strong>drafts</strong> — they may contain errors,
              inaccuracies, or omissions. You are solely responsible for reviewing, validating, and
              deciding whether to act on AI-generated content. ProductMind makes no guarantees
              regarding the accuracy, completeness, or suitability of AI outputs for any purpose.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">6. Data ownership</h2>
            <p className="mt-2">
              You retain ownership of all data you input into ProductMind. We do not claim
              ownership of your projects, feedback, or other content. AI-generated outputs are
              provided for your use within the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">7. Service limits</h2>
            <p className="mt-2">
              AI features are subject to rate limits to ensure fair usage and service stability.
              Current limits are displayed in the app. Limits may be adjusted during the beta period.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">8. Termination</h2>
            <p className="mt-2">
              You may delete your account at any time from Settings. We reserve the right to suspend
              or terminate accounts that violate these terms or abuse the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">9. Limitation of liability</h2>
            <p className="mt-2">
              ProductMind is provided &quot;as is&quot; and &quot;as available&quot; without warranties
              of any kind, express or implied. We are not liable for any damages arising from the use
              of the service, reliance on AI-generated content, data loss, service interruptions, or
              any decisions made based on outputs from the platform.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">10. Changes to terms</h2>
            <p className="mt-2">
              We may update these terms as ProductMind evolves. Continued use of the service after
              changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">11. Contact</h2>
            <p className="mt-2">
              For questions about these terms, contact us at{" "}
              <span className="font-medium text-brand-600">legal@productmind.app</span>.
            </p>
          </section>
        </div>

        <div className="mt-12 border-t border-gray-200 pt-6">
          <Link href="/" className="text-sm font-medium text-brand-600 hover:text-brand-700">
            ← Back to home
          </Link>
        </div>
      </main>
    </div>
  );
}
