import Link from "next/link";
import { IconSparkles } from "@/components/icons";

export const metadata = {
  title: "Terms of Service – ProductMind",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <header className="border-b border-gray-200 bg-white">
        <div className="mx-auto flex max-w-3xl items-center gap-3 px-6 py-6">
          <Link href="/" className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-600">
              <IconSparkles className="h-4 w-4 text-white" />
            </div>
            <span className="text-lg font-bold text-gray-900">ProductMind</span>
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-12">
        <h1 className="text-3xl font-bold text-gray-900">Terms of Service</h1>
        <p className="mt-2 text-sm text-gray-500">Last updated: May 2026</p>

        <div className="mt-8 space-y-8 text-sm leading-relaxed text-gray-700">
          <section>
            <h2 className="text-lg font-semibold text-gray-900">1. Acceptance</h2>
            <p className="mt-2">
              By accessing or using ProductMind, you agree to be bound by these Terms of Service.
              If you do not agree, do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">2. Service description</h2>
            <p className="mt-2">
              ProductMind is an AI-powered product decision assistant. It provides tools for
              generating PRDs, competitive analyses, roadmaps, feature prioritization, and
              strategic insights using artificial intelligence.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">3. User responsibilities</h2>
            <p className="mt-2">
              You are responsible for maintaining the confidentiality of your account credentials
              and for all activities under your account. You agree not to misuse the service or
              use it for unlawful purposes.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">4. AI-generated content</h2>
            <p className="mt-2">
              Content generated by AI is provided as-is for informational and decision-support
              purposes. It should not be treated as professional advice. You are responsible for
              reviewing and validating AI outputs before acting on them.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">5. Data ownership</h2>
            <p className="mt-2">
              You retain ownership of all data you input into ProductMind. We do not claim
              ownership of your projects, feedback, or other content.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">6. Termination</h2>
            <p className="mt-2">
              You may delete your account at any time. We reserve the right to suspend or
              terminate accounts that violate these terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">7. Limitation of liability</h2>
            <p className="mt-2">
              ProductMind is provided &quot;as is&quot; without warranties of any kind. We are not
              liable for any damages arising from the use of the service or reliance on
              AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900">8. Contact</h2>
            <p className="mt-2">
              For questions about these terms, contact us at{" "}
              <span className="font-medium text-brand-600">legal@productmind.app</span>.
            </p>
          </section>

          {/* TODO: Add governing law, dispute resolution, and jurisdiction clauses before production launch */}
        </div>

        <div className="mt-12 border-t border-gray-200 pt-6">
          <Link href="/" className="text-sm font-medium text-brand-600 hover:text-brand-700">
            ← Back to home
          </Link>
        </div>
      </main>
    </div>
  );
}

